# Generated by Django 2.0.2 on 2018-03-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-end_date', 'id'], 'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-end_date', 'id']},
        ),
    ]
