# Generated by Django 2.0.2 on 2018-03-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_auto_20180305_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='linkname',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
