# Generated by Django 2.0.2 on 2018-03-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_auto_20180305_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('authors', models.TextField()),
                ('author_underlined', models.CharField(max_length=50)),
                ('journal', models.CharField(max_length=150)),
                ('year', models.IntegerField(default=2018)),
                ('order', models.IntegerField(default=1)),
                ('journalpages', models.TextField(blank=True)),
                ('link', models.URLField(blank=True, verbose_name='Publication URL')),
            ],
            options={
                'db_table': 'publications',
                'ordering': ['-year', 'order'],
            },
        ),
    ]
