# Generated by Django 2.0.2 on 2018-03-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='author_underlined',
            field=models.CharField(default='Marin A.', max_length=50),
        ),
    ]
