# Generated by Django 2.0.2 on 2018-03-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_auto_20180305_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='picture',
            field=models.URLField(blank=True),
        ),
    ]
