# Generated by Django 2.0.2 on 2018-03-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_project_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
