# Generated by Django 2.0.2 on 2018-03-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0019_remove_achievement_linkname'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='location2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='education',
            name='schoolurl2',
            field=models.URLField(blank=True, verbose_name='School URL'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='author_underlined',
            field=models.CharField(default='Marin A', max_length=50),
        ),
    ]
