# Generated by Django 2.0.2 on 2018-03-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0020_auto_20180305_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='name2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='education',
            name='schoolurl2',
            field=models.URLField(blank=True, verbose_name='School URL2'),
        ),
    ]
