# Generated by Django 2.0.2 on 2018-03-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0022_auto_20180306_0750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['level', 'order']},
        ),
        migrations.AddField(
            model_name='language',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
