# Generated by Django 2.0.2 on 2018-03-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0027_auto_20180307_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='suffix',
            field=models.CharField(blank=True, help_text='e.g. PhD', max_length=255),
        ),
    ]
