# Generated by Django 2.0.2 on 2018-03-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0032_ongoingproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ongoingproject',
            name='ongoing',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ongoing',
        ),
    ]
