# Generated by Django 2.0.2 on 2018-03-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0033_auto_20180308_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['order', 'id'],
                'verbose_name_plural': '11. ProjectTypes',
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', 'id'], 'verbose_name_plural': '12. Projects'},
        ),
    ]
