# Generated by Django 2.0.2 on 2018-03-10 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0034_auto_20180310_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.ProjectType'),
        ),
    ]
