# Generated by Django 2.0.2 on 2018-03-10 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0035_project_projtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OngoingProject',
        ),
    ]
