# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-01 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0036_delete_ongoingproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name=b'picture',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'static/resume/img/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'static/resume/img/'),
        ),
    ]
