# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-17 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=1)),
                ('url', models.URLField(blank=True, verbose_name=b'URL')),
            ],
            options={
                'ordering': ['order', 'id'],
                'db_table': 'achievement',
                'verbose_name_plural': '13. Achievements',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('name2', models.CharField(blank=True, max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('location2', models.CharField(blank=True, max_length=250)),
                ('schoolurl', models.URLField(blank=True, verbose_name=b'School URL')),
                ('schoolurl2', models.URLField(blank=True, verbose_name=b'School URL2')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('degree', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-end_date', 'id'],
                'verbose_name_plural': '03. Education',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=250)),
                ('companyurl', models.URLField(verbose_name=b'Company URL')),
                ('location', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('company_image', models.CharField(blank=True, help_text=b'path to company image, local or otherwise', max_length=250)),
            ],
            options={
                'ordering': ['-end_date', 'id'],
                'db_table': 'jobs',
                'verbose_name_plural': '04. Jobs',
            },
        ),
        migrations.CreateModel(
            name='JobAccomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Job')),
            ],
            options={
                'ordering': ['order', 'id'],
                'db_table': 'jobaccomplishment',
                'verbose_name_plural': '05. Job Accomplishments',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
                ('order', models.IntegerField(default=1)),
                ('level', models.IntegerField(choices=[(5, b'Native'), (4, b'Full professional proficiency'), (3, b'Professional working proficiency'), (2, b'Limited professional proficiency'), (1, b'Elementary professional proficiency')], default=5, help_text=b'Choice between 1 and 5')),
            ],
            options={
                'ordering': ['level', 'order'],
                'verbose_name_plural': '10. Languages',
            },
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': '02. Overview',
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('suffix', models.CharField(blank=True, help_text=b'e.g. PhD', max_length=255)),
                ('locality', models.CharField(help_text=b'e.g. city such as Boston', max_length=255)),
                ('region', models.CharField(blank=True, help_text=b'e.g. MA or Italy', max_length=255)),
                ('title', models.CharField(blank=True, help_text=b'e.g. Developer', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('site', models.URLField(blank=True)),
                ('twittername', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to=b'static/resume/img/')),
            ],
            options={
                'verbose_name_plural': '01. Personal Info',
            },
        ),
        migrations.CreateModel(
            name='ProgrammingArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['order', 'name'],
                'verbose_name_plural': '08. Programming areas',
            },
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('level', models.IntegerField(choices=[(5, b'Expert'), (4, b'Advanced'), (3, b'Intermediate'), (2, b'Novice'), (1, b'Fundamental Awareness')], help_text=b'Choice between 1 and 5')),
                ('description', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=1)),
                ('programmingarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.ProgrammingArea')),
            ],
            options={
                'ordering': ['order', 'id'],
                'db_table': 'programminglanguage',
                'verbose_name_plural': '09. Programming languages',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True, help_text=b'Text shown in project list')),
                ('long_description', models.TextField(blank=True, help_text=b'Text shown in modals appearing when clicking on images')),
                ('link', models.URLField(blank=True)),
                ('order', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, help_text=b'Preferred width x height: 247x200', upload_to=b'static/resume/img/')),
            ],
            options={
                'ordering': ['order', 'id'],
                'verbose_name_plural': '12. Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['order', 'id'],
                'verbose_name_plural': '11. ProjectTypes',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('authors', models.TextField()),
                ('author_underlined', models.CharField(default=b'Marin A', max_length=50)),
                ('journal', models.CharField(max_length=150)),
                ('year', models.IntegerField(default=2018)),
                ('order', models.IntegerField(default=1)),
                ('journalpages', models.TextField(blank=True)),
                ('link', models.URLField(blank=True, verbose_name=b'Publication URL')),
            ],
            options={
                'ordering': ['-year', 'order'],
                'db_table': 'publications',
                'verbose_name_plural': '14. Publications',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['order', 'id'],
                'verbose_name_plural': '07. Skills',
            },
        ),
        migrations.CreateModel(
            name='Skillset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '06. Skillsets',
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='skillset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Skillset'),
        ),
        migrations.AddField(
            model_name='project',
            name='projtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.ProjectType'),
        ),
    ]
