# Generated by Django 2.0.2 on 2018-03-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programminglanguage',
            name='vote',
        ),
        migrations.AddField(
            model_name='programminglanguage',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='level',
            field=models.CharField(choices=[(5, 'Expert'), (4, 'Advanced'), (3, 'Intermediate'), (2, 'Novice'), (1, 'Fundamental Awareness')], help_text='Choice between 1 and 5', max_length=1),
        ),
    ]
