# Generated by Django 2.0.2 on 2018-03-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_auto_20180305_0912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
