# Generated by Django 2.0.2 on 2018-03-06 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0018_achievement_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='linkname',
        ),
    ]
