# Generated by Django 2.0.2 on 2018-03-07 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0025_auto_20180307_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='text',
        ),
    ]
