# Generated by Django 2.0.2 on 2018-03-08 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0026_auto_20180307_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overview',
            options={'verbose_name_plural': '02. Overview'},
        ),
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'verbose_name_plural': '01. Personal Info'},
        ),
    ]
