# Generated by Django 2.0.2 on 2018-03-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0030_project_ongoing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
