# Generated by Django 2.0.2 on 2018-03-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0031_auto_20180308_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='OngoingProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('order', models.IntegerField(default=1)),
                ('picture', models.CharField(blank=True, max_length=150)),
                ('ongoing', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '12. Ongoing Projects',
                'ordering': ['order', 'id'],
            },
        ),
    ]
