# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-10 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0037_auto_20180401_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name=b'description',
        ),
        migrations.AddField(
            model_name='project',
            name='long_description',
            field=models.TextField(blank=True, help_text=b'Text shown in modals appearing when clicking on images'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.TextField(blank=True, help_text=b'Text shown in project list'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text=b'Preferred width x height: 247x200', upload_to=b'static/resume/img/'),
        ),
    ]
